{% set version = '0.6.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-docxtractr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/docxtractr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/docxtractr/docxtractr_{{ version }}.tar.gz
  sha256: 3c42b8b3a6edd78e48d80392a6b35748f3a982d833734d9ae80b3a0d5e2271ce

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-dplyr
    - r-httr
    - r-magrittr
    - r-purrr
    - r-xml2

  run:
    - r-base
    - r-dplyr
    - r-httr
    - r-magrittr
    - r-purrr
    - r-xml2

test:
  commands:
    - $R -e "library('docxtractr')"           # [not win]
    - "\"%R%\" -e \"library('docxtractr')\""  # [win]

about:
  home: http://gitlab.com/hrbrmstr/docxtractr
  license: MIT
  summary: '''Microsoft Word'' ''docx'' files provide an ''XML'' structure that is fairly straightforward
    to navigate, especially when it applies to ''Word'' tables and comments. Tools are
    provided to determine table count/structure, comment count and also to extract/clean
    tables and comments from ''Microsoft Word'' ''docx'' documents. There is also nascent
    support for ''.doc'' and ''.pptx'' files.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: docxtractr
# Title: Extract Data Tables and Comments from 'Microsoft' 'Word' Documents
# Version: 0.6.5
# Authors@R: c( person("Bob", "Rudis", email = "bob@rud.is", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-5670-2640")), person("Mark", "Dulhunty", role = c("ctb")), person("Karlo", "Guidoni-Martins", role = c("ctb"), email = "kguidonimartins@gmail.com"), person("Chris", "Muir", email = "chrismuirrva@gmail.com", role = c("aut", "ctb")), person(given = "John", family = "Muschelli", role =  "ctb", email = "muschellij2@gmail.com") )
# Maintainer: Bob Rudis <bob@rud.is>
# Description: 'Microsoft Word' 'docx' files provide an 'XML' structure that is fairly straightforward to navigate, especially when it applies to 'Word' tables and comments. Tools are provided to determine table count/structure, comment count and also to extract/clean tables and comments from 'Microsoft Word' 'docx' documents. There is also nascent support for '.doc' and '.pptx' files.
# SystemRequirements: LibreOffice (<https://www.libreoffice.org/>) required to extract data from .doc files or perform .pptx conversion.
# URL: http://gitlab.com/hrbrmstr/docxtractr
# BugReports: https://gitlab.com/hrbrmstr/docxtractr/issues
# Encoding: UTF-8
# Depends: R (>= 3.6.0)
# License: MIT + file LICENSE
# LazyData: true
# Suggests: covr, tinytest
# Imports: tools, xml2, purrr, dplyr, utils, httr, magrittr
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2020-07-04 13:11:16 UTC; hrbrmstr
# Author: Bob Rudis [aut, cre] (<https://orcid.org/0000-0001-5670-2640>), Mark Dulhunty [ctb], Karlo Guidoni-Martins [ctb], Chris Muir [aut, ctb], John Muschelli [ctb]
# Repository: CRAN
# Date/Publication: 2020-07-05 04:50:41 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
